<x-app-layout>
    <div>
        <div class="max-w-screen mx-auto bg-gray-900 px-2 py-10 sm:px-6 lg:px-8">
            <x-card title="DeepskyLog Image Catalogs">
                <div class="mt-4">
                    <table class="table">
                        <tr><th class="catalog">{!! __("Catalogs sorted by name") !!}</th></tr>
                        <tr><td><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/Abell.pdf">{!! __("Abell Planetary Nebulae") !!}</a></td></tr>
                    </table>
                    <br />
                    <table class="table">
                        <tr><th colspan="3" class="catalog">{!! __("Catalogs sorted by constellation") !!}</th></tr>
                        <tr></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/AND.pdf">Andromeda</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/ANT.pdf">Antlia</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/AQR.pdf">Aquarius</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/AQL.pdf">Aquila</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/ARI.pdf">Aries</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/AUR.pdf">Auriga</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/BOO.pdf">Bootes</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CAE.pdf">Caelum</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CAM.pdf">Camelopardalis</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CNC.pdf">Cancer</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CVN.pdf">Canes Venatici</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CMA.pdf">Canis Major</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CMI.pdf">Canis Minor</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CAP.pdf">Capricornus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CAS.pdf">Cassiopeia</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CEN.pdf">Centaurus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CEP.pdf">Cepheus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CET.pdf">Cetus</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/COL.pdf">Columba</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/COM.pdf">Coma Berenices</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CRA.pdf">Corona Australis</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CRB.pdf">Corona Borealis</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CRV.pdf">Corvus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CRT.pdf">Crater</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/CYG.pdf">Cygnus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/DEL.pdf">Delphinus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/DRA.pdf">Draco</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/EQU.pdf">Equuleus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/ERI.pdf">Eridanus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/FOR.pdf">Fornax</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/GEM.pdf">Gemini</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/GRU.pdf">Grus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/HER.pdf">Hercules</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/HOR.pdf">Horologium</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/HYA.pdf">Hydra</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/LAC.pdf">Lacerta</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/LEO.pdf">Leo</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/LMI.pdf">Leo Minor</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/LEP.pdf">Lepus</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/LIB.pdf">Libra</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/LUP.pdf">Lupus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/LYN.pdf">Lynx</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/LYR.pdf">Lyra</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/MIC.pdf">Microscopium</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/MON.pdf">Monoceros</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/OPH.pdf">Ophiuchus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/ORI.pdf">Orion</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/PEG.pdf">Pegasus</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/PER.pdf">Perseus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/PHE.pdf">Phoenix</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/PSC.pdf">Pisces</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/PSA.pdf">Pisces Austrinus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/PUP.pdf">Puppis</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/PYX.pdf">Pyxis</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/SGE.pdf">Sagitta</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/SGR.pdf">Sagittarius</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/SCO.pdf">Scorpius</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/SCL.pdf">Sculptor</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/SCT.pdf">Scutum</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/SER.pdf">Serpens</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/TAU.pdf">Taurus</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/TRI.pdf">Triangulum</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/UMA.pdf">Ursa Major</a></td></tr>
                        <tr><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/UMI.pdf">Ursa Minor</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/VIR.pdf">Virgo</a></td><td class="catalog"><a href="https://www.deepskylog.org/DSL/astroimagecatalogs/constellations/VUL.pdf">Vulpecula</a></td></tr>
                    </table>
                </div>
            </x-card>
        </div>
    </div>
</x-app-layout>
